name: test_CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, linux]
    steps:
      - name: Check
        uses: actions/checkout@v4
      - name: set up python3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - run: python insert.py
      - run: pip3 install pandas

