name: test_CI
on:
  push:
    branches:
      - main

jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: [self-hosted, linux]
    steps:
      - name: Check
        uses: actions/checkout@v4
      - name: set up python3.9
        uses: actions/setup-python3@v3
        with:
          python-version: '3.9'
      - name: install python packeg
        run: |
          pip3 install pandas
          python3 insert.py
